version: '1'
services:
  eurekaserver:
     image:   joaobatista/tmx-eurekasvr:chapter9
     ports:
       - "8761:8761"
  configserver:
      image: joaobatista/tmx-confsvr:chapter9
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
      image: joaobatista/tmx-zuulsvr:chapter9
      ports:
        - "5555:5555"
      environment:
        PROFILE: "default"
        SERVER_PORT: "5555"
        DATABASESERVER_PORT: "5432"
        CONFIGSERVER_PORT: "8888"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  database:
      image: postgres:9.5
      ports:
      - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=eagle_eye_local
  licensingservice:
      image: joaobatista/tmx-licensing-service:chapter9
      ports:
        - "8080:8080"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        ES_PORT:           "9200"
        DATABASE_PORT:     "5432"
        CONFIGSERVER_PORT: "8888"
        EUREKASERVER_PORT: "8761"
        AUTHSERVER_PORT:   "8091"
        ZUULSERVER_PORT:   "5555"
        KAFKASERVER_PORT:  "2181"
        REDIS_PORT:        "6379"
        ENCRYPT_KEY:       "IMSYMMETRIC"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"
  organizationservice:
      image: joaobatista/tmx-organization-service:chapter9
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        DATABASE_PORT:     "5432"
        CONFIGSERVER_PORT: "8888"
        EUREKASERVER_PORT: "8761"
        AUTHSERVER_PORT:   "8091"
        ZUULSERVER_PORT:   "5555"
        KAFKASERVER_PORT:  "2181"
        ENCRYPT_KEY:       "IMSYMMETRIC"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"
  authenticationservice:
      image: joaobatista/tmx-authentication-service:chapter9
      ports:
        - "8901:8901"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8901"
        DATABASE_PORT:     "5432"
        CONFIGSERVER_PORT: "8888"
        EUREKASERVER_PORT: "8761"
        ENCRYPT_KEY:       "IMSYMMETRIC"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  orgservice-new:
    image: joaobatista/tmx-orgservice-new:chapter9
    ports:
      - "8087:8087"
    environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        DATABASE_PORT:     "5432"
        CONFIGSERVER_PORT: "8888"
        EUREKASERVER_PORT: "8761"
        AUTHSERVER_PORT:   "8091"
        ZUULSERVER_PORT:   "5555"
        KAFKASERVER_PORT:  "2181"
        ENCRYPT_KEY:       "IMSYMMETRIC"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
        KAFKASERVER_URI: "kafkaserver"
        ZKSERVER_URI: "kafkaserver"
  specialroutes-service:
    image: joaobatista/tmx-specialroutes-service:chapter9
    ports:
      - "8910:8910"
    environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        DATABASE_PORT:     "5432"
        CONFIGSERVER_PORT: "8888"
        EUREKASERVER_PORT: "8761"
        AUTHSERVER_PORT:   "8091"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
