version: '1'
services:
  eurekaserver:
     image:   joaobatista/tmx-eurekasvr:chapter6
     ports:
       - "8761:8761"
  configserver:
      image: joaobatista/tmx-confsvr:chapter6
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         EUREKASERVER_PORT: "8761"
         ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
    image: joaobatista/tmx-zuulsvr:chapter6
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ORGSERVERNEW_PORT:        "8087"
  database:
      image: postgres:9.5
      ports:
      - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=p0stgr@s
        - POSTGRES_DB=eagle_eye_local
  licensingservice:
      image: joaobatista/licensing-service:chapter6
      ports:
        - "8080:8080"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice:
      image: joaobatista/tmx-organization-service:chapter6
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  orgservice-new:
    image: joaobatista/tmx-orgservice-new:chapter6
    ports:
      - "8087:8087"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8087"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  specialroutes-service:
    image: joaobatista/tmx-specialroutes-service:chapter6
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"
      ENCRYPT_KEY:       "IMSYMMETRIC"


